name: SYLENTH 24/7

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 */4 * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Python o'rnatish
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Kutubxonalar
        run: pip install -r requirements.txt

      - name: Botni ishga tushirish
        env:
          BOT_TOKEN:    ${{ secrets.BOT_TOKEN }}
          DEEPSEEK_KEY: ${{ secrets.DEEPSEEK_KEY }}
          ADMIN_ID:     ${{ secrets.ADMIN_ID }}
        run: timeout 14000 python main.py || true
